apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: sysdigagents.sysdig.com
spec:
  group: sysdig.com
  names:
    kind: SysdigAgent
    listKind: SysdigAgentList
    plural: sysdigagents
    singular: sysdigagent
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
