apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: sysdigagents.sysdig.com
spec:
  group: sysdig.com
  names:
    kind: SysdigAgent
    listKind: SysdigAgentList
    plural: sysdigagents
    singular: sysdigagent
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1
    served: true
    storage: true
  - name: v1alpha1
    served: false
    storage: false
