apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: sysdig-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Sysdig is a unified platform for container and microservices monitoring,
    troubleshooting, security and forensics. Sysdig platform has been built on top
    of Sysdig tool and Sysdig Inspect open-source technologies.
  displayName: Sysdig Agent Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - monitoring
  - security
  - alerting
  - metrics
  - troubleshooting
  - run-time
  - syscall
  links:
  - name: Sysdig Operator
    url: https://sysdig-operator.domain
  maintainers:
  - email: ashwin.chandrasekar@sysdig.com
    name: Ashwin Chandrasekar
  maturity: alpha
  provider:
    name: Sysdig
    url: https://sysdig.com
  version: 0.0.0
