apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysdig-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sysdig-operator
  template:
    metadata:
      labels:
        name: sysdig-operator
    spec:
      serviceAccountName: sysdig-operator
      containers:
        - name: sysdig-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "sysdig-operator"
            - name: RELATED_IMAGE_REGISTRY_DAEMONSET
              value: "docker.io"
            - name: RELATED_IMAGE_REPOSITORY_DAEMONSET
              value: "sysdig/agent"
            - name: RELATED_IMAGE_TAG_DAEMONSET
              value: REPLACE_AGENT_VERSION
