apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysdig-agent-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sysdig-agent-operator
  template:
    metadata:
      labels:
        name: sysdig-agent-operator
    spec:
      serviceAccountName: sysdig-agent-operator
      containers:
        - name: sysdig-agent-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "sysdig-agent-operator"
