apiVersion: sysdig.com/v1
kind: SysdigAgent
metadata:
  name: sysdigagent-sample
spec:
  # Default values copied from <project_dir>/helm-charts/sysdig/values.yaml
  auditLog:
    auditServerPort: 7765
    auditServerUrl: 0.0.0.0
    dynamicBackend:
      enabled: false
    enabled: false
  clusterName: ""
  collectorSettings:
    collectorHost: null
    collectorPort: null
    ssl: null
    sslVerifyCertificate: null
  customAppChecks: {}
  daemonset:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - amd64
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
          - matchExpressions:
            - key: beta.kubernetes.io/arch
              operator: In
              values:
              - amd64
            - key: beta.kubernetes.io/os
              operator: In
              values:
              - linux
    annotations: {}
    env: {}
    nodeSelector: {}
    probes:
      initialDelay: 90
    updateStrategy:
      type: RollingUpdate
  ebpf:
    enabled: false
    settings:
      mountEtcVolume: true
  extraVolumes:
    mounts: []
    volumes: []
  image:
    overrideValue: null
    pullPolicy: IfNotPresent
    registry: quay.io
    repository: sysdig/agent
    tag: 12.1.1
  leaderelection:
    enable: false
  nodeAnalyzer:
    apiEndpoint: ""
    benchmarkRunner:
      image:
        pullPolicy: IfNotPresent
        repository: sysdig/compliance-benchmark-runner
        tag: 1.0.6.0
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 150m
          memory: 128Mi
    debug: false
    deploy: true
    hostAnalyzer:
      image:
        pullPolicy: IfNotPresent
        repository: sysdig/host-analyzer
        tag: 0.1.3
      resources:
        limits:
          cpu: 500m
          memory: 1536Mi
        requests:
          cpu: 150m
          memory: 512Mi
      schedule: '@dailydefault'
    httpProxy: null
    httpsProxy: null
    imageAnalyzer:
      extraVolumes:
        mounts: []
        volumes: []
      image:
        pullPolicy: IfNotPresent
        repository: sysdig/node-image-analyzer
        tag: 0.1.15
      resources:
        limits:
          cpu: 500m
          memory: 1536Mi
        requests:
          cpu: 150m
          memory: 512Mi
    noProxy: null
    priorityClassName: null
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  nodeImageAnalyzer:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - amd64
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
          - matchExpressions:
            - key: beta.kubernetes.io/arch
              operator: In
              values:
              - amd64
            - key: beta.kubernetes.io/os
              operator: In
              values:
              - linux
    deploy: false
    extraVolumes:
      mounts: []
      volumes: []
    image:
      pullPolicy: IfNotPresent
      repository: sysdig/node-image-analyzer
      tag: 0.1.15
    priorityClassName: null
    resources:
      limits:
        cpu: 500m
        memory: 1024Mi
      requests:
        cpu: 250m
        memory: 512Mi
    settings:
      debug: false
      httpProxy: null
      httpsProxy: null
      noProxy: null
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  priorityClassName: null
  prometheus:
    file: false
    yaml: {}
  proxy:
    httpProxy: null
    httpsProxy: null
    noProxy: null
  psp:
    create: true
  rbac:
    create: true
  resourceProfile: small
  scc:
    create: true
  secure:
    enabled: true
  serviceAccount:
    create: true
    name: null
  slim:
    enabled: false
    image:
      repository: sysdig/agent-slim
    kmoduleImage:
      repository: sysdig/agent-kmodule
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 1000m
        memory: 348Mi
  sysdig:
    accessKey: ""
    disableCaptures: false
    existingAccessKeySecret: ""
    settings: {}
  timezone: null
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  
  
