apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: foo-sysdig-operator-crd
  app.kubernetes.io/managed-by: sysdig-operator
  app.kubernetes.io/name: sysdig-operator-crd
resources:
- sysdig.crd.base.yaml
